### ISSUE TITLE
Documentation for the "execute_api" step

### ISSUE THREAD

**Issue by glasswalk3r** [cpan-testers/cpantesters-deploy#8]
>> For instance, what tests can I execute after execute_api? How do I
>> execute them?
> 
> Once a box has been prepared with prepare_api, you can use the Rexfile
> in the cpantesters-api repository to deploy the API into the VM. I can
> add this information to the docs.

**Comment by preaction** [comment]
There is no execute_api step. I asked you a question about what I could add to the docs, and then I mentioned that you could, yourself, add to the docs.

I also added this commit 5 days before this issue was opened: https://github.com/cpan-testers/cpantesters-deploy/commit/e9b81de85a0c227bcfa3cd87d3ebba02a856db5b

And I added this commit a day before this issue was opened: https://github.com/cpan-testers/cpantesters-deploy/commit/a70713a6a11654e5e8784dc66d1923a1df62ed4e

Do these commits satisfy your curiosity?
